### ISSUE TITLE
tidk plot -h conflicts

### ISSUE THREAD

**Issue by DamonChen-slu** [tolkit/telomeric-identifier#12]
Hi,
When I tried to plot the tidk finder result ran into this error message:
```
tidk plot -c finder/idk_find.csv -o find_default
thread 'main' panicked at '`help`s `-h` conflicts with `height`.

To change `help`s short, call `cmd.arg(Arg::new("help")...)`.', /home/conda/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.1/src/build/command.rs:4249:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and I installed tidk by conda and here is the version number:

> Name                    Version                   Build  Channel
>tidk                      0.1.5                h87f3376_1    bioconda

I have totally no knowledge of rust so I cannot solve it by myself.
Thank you for your time and pacience!

**Comment by Euphrasiologist** [comment]
Hello,

I encountered this bug a week or so back. It's fixed in the latest version `0.2.0`, but I have yet to update this to conda. I will try and do that ASAP and let you know. Otherwise if you are desperate you can install the Rust toolchain, clone this repository and compile it yourself.

Thanks!
M

**Comment by DamonChen-slu** [comment]
> 

Thank you for your prompt reply! I prefer to wait for you to release the updated version. 😄

**Comment by Euphrasiologist** [comment]
On bioconda now:

https://anaconda.org/bioconda/tidk

Let me know if it works!
